sudo: required
services:
  - docker

before_install:
  - docker build -t anton-prymak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anton-prymak/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-new"
  env: "DockerReactNew-env"
  bucket_name: "elasticbeanstalk-eu-central-1-842943009896"
  bucket_path: "docker-react-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY_ID